# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simtool < Formula
  desc "Terminal UI for iOS Simulator management"
  homepage "https://github.com/azizuysal/simtool"
  version "1.1.0"
  license "MIT"

  depends_on "go" => :build
  depends_on :macos

  url "https://github.com/azizuysal/simtool/releases/download/v1.1.0/simtool_1.1.0_darwin_all.tar.gz"
  sha256 "866fd67f8349e691c1f9af3d64a43bf6ed82d5d207b14d2badc9deb6a81c8799"

  define_method(:install) do
    bin.install "simtool"
  end

  test do
    system "#{bin}/simtool", "--version"
  end
end
