# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simtool < Formula
  desc "Terminal UI for iOS Simulator management"
  homepage "https://github.com/azizuysal/simtool"
  version "1.1.1"
  license "MIT"

  depends_on "go" => :build
  depends_on :macos

  url "https://github.com/azizuysal/simtool/releases/download/v1.1.1/simtool_1.1.1_darwin_all.tar.gz"
  sha256 "9bff4e48f93b3555c21acad79e92634d2d00b0782148d13d2a4d6a1ffb12370c"

  define_method(:install) do
    bin.install "simtool"
  end

  test do
    system "#{bin}/simtool", "--version"
  end
end
