# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simtool < Formula
  desc "Terminal UI for iOS Simulator management"
  homepage "https://github.com/azizuysal/simtool"
  version "1.0.2"
  license "MIT"

  depends_on "go" => :build
  depends_on :macos

  url "https://github.com/azizuysal/simtool/releases/download/v1.0.2/simtool_1.0.2_darwin_all.tar.gz"
  sha256 "8d939e436a3b1a440fd17e553d2d353c3f2f195cd33cea40c6e44fea3556ade4"

  def install
    bin.install "simtool"
  end

  test do
    system "#{bin}/simtool", "--version"
  end
end
